---
- name: Configure block device partitions
  ansible.builtin.include_tasks: parted.yml
  when: parted is defined and parted|count > 0

- name: Configure mdadm arrays
  ansible.builtin.include_tasks: mdadm.yml
  when: mdadm is defined and mdadm|count > 0

- name: Configure LVM volume groups
  ansible.builtin.include_tasks: lvg.yml
  when: lvg is defined and lvg|count > 0

- name: Configure LVM logical volumes
  ansible.builtin.include_tasks: lvol.yml
  when: lvol is defined and lvol|count > 0

- name: Makes a filesystem
  ansible.builtin.include_tasks: filesystem.yml
  when: filesystem is defined and filesystem|count > 0

- name: Control active and configured mount points
  ansible.builtin.include_tasks: mount.yml
  when: mount is defined and mount|count > 0
